
import React, { useEffect, useState } from 'react';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, LineChart, Line } from 'recharts';
import { Activity, Users, AlertTriangle, BedDouble, Map, Globe, BrainCircuit, FileText, CheckCircle2, Ambulance, Network } from 'lucide-react';
import { getExecutiveBriefing, getStatewideResourcePlan, ExecutiveBriefing, StatewideCrisisPlan } from '../services/geminiService';
import { MOCK_REFERRALS } from '../constants';

const data = [
  { name: 'Visakhapatnam', admissions: 145, discharges: 130 },
  { name: 'Vijayawada', admissions: 152, discharges: 135 },
  { name: 'Guntur', admissions: 148, discharges: 140 },
  { name: 'Tirupati', admissions: 161, discharges: 145 },
  { name: 'Kurnool', admissions: 155, discharges: 148 },
  { name: 'Nellore', admissions: 140, discharges: 125 },
  { name: 'Anantapur', admissions: 135, discharges: 120 },
];

const riskData = [
  { name: '00:00', risk: 12 },
  { name: '04:00', risk: 15 },
  { name: '08:00', risk: 45 },
  { name: '12:00', risk: 38 },
  { name: '16:00', risk: 55 },
  { name: '20:00', risk: 25 },
];

export const Dashboard: React.FC = () => {
  const [briefing, setBriefing] = useState<ExecutiveBriefing | null>(null);
  const [crisisPlan, setCrisisPlan] = useState<StatewideCrisisPlan | null>(null);

  useEffect(() => {
    const fetchAI = async () => {
      // Mock metrics passed to AI
      const metrics = {
        activeCases: 14248,
        icuOccupancy: "87%",
        criticalAlerts: 142,
        regions: ["Visakhapatnam", "NTR", "Guntur"],
        trends: "Rising vector borne diseases in coastal belt"
      };
      
      const [briefingRes, crisisRes] = await Promise.all([
        getExecutiveBriefing(metrics),
        getStatewideResourcePlan(metrics)
      ]);
      
      setBriefing(briefingRes);
      setCrisisPlan(crisisRes);
    };
    fetchAI();
  }, []);

  return (
    <div className="space-y-6 animate-in fade-in duration-300">
      
      {/* AI Executive Briefing */}
      <div className="bg-slate-900 rounded-xl p-6 text-white shadow-xl border border-slate-700 relative overflow-hidden">
        <div className="absolute top-0 right-0 w-64 h-64 bg-emerald-500/10 rounded-full blur-3xl -mr-16 -mt-16"></div>
        <div className="relative z-10">
           <div className="flex items-center gap-3 mb-4">
              <div className="p-2 bg-emerald-500/20 rounded-lg border border-emerald-500/30">
                 <BrainCircuit className="h-6 w-6 text-emerald-400" />
              </div>
              <div>
                 <h2 className="text-lg font-bold">Principal Secretary's Morning Briefing</h2>
                 <p className="text-xs text-slate-400">Generated by State Health AI • {new Date().toLocaleDateString()}</p>
              </div>
           </div>
           
           {briefing ? (
             <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                <div className="bg-white/5 rounded-lg p-4 border border-white/10">
                   <h3 className="text-emerald-400 text-xs font-bold uppercase tracking-wider mb-2 flex items-center gap-2">
                     <Activity className="h-3 w-3" /> Situation Report
                   </h3>
                   <p className="text-sm text-slate-200 leading-relaxed">
                      {briefing.situationReport}
                   </p>
                </div>
                <div className="bg-white/5 rounded-lg p-4 border border-white/10">
                   <h3 className="text-amber-400 text-xs font-bold uppercase tracking-wider mb-2 flex items-center gap-2">
                     <AlertTriangle className="h-3 w-3" /> Critical Alerts
                   </h3>
                   <ul className="space-y-2">
                      {briefing.criticalAlerts.map((alert, i) => (
                        <li key={i} className="text-sm text-slate-200 flex items-start gap-2">
                           <span className="text-amber-500 mt-1">•</span> {alert}
                        </li>
                      ))}
                   </ul>
                </div>
                <div className="bg-white/5 rounded-lg p-4 border border-white/10">
                   <h3 className="text-blue-400 text-xs font-bold uppercase tracking-wider mb-2 flex items-center gap-2">
                     <FileText className="h-3 w-3" /> Recommended Actions
                   </h3>
                   <ul className="space-y-2">
                      {briefing.recommendedActions.map((action, i) => (
                        <li key={i} className="text-sm text-slate-200 flex items-start gap-2">
                           <span className="text-blue-500 mt-1">→</span> {action}
                        </li>
                      ))}
                   </ul>
                </div>
             </div>
           ) : (
             <div className="animate-pulse flex space-x-4">
               <div className="flex-1 space-y-4 py-1">
                 <div className="h-4 bg-slate-700 rounded w-3/4"></div>
                 <div className="space-y-2">
                   <div className="h-4 bg-slate-700 rounded"></div>
                   <div className="h-4 bg-slate-700 rounded w-5/6"></div>
                 </div>
               </div>
             </div>
           )}
        </div>
      </div>

      {/* KPI Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        <div className="bg-white p-6 rounded-xl shadow-sm border border-slate-100">
          <div className="flex justify-between items-start">
            <div>
              <p className="text-sm text-slate-500 font-medium">State Active Cases</p>
              <h3 className="text-3xl font-bold text-slate-900 mt-2">14,248</h3>
            </div>
            <div className="p-3 bg-blue-50 rounded-lg text-blue-600">
              <Globe className="h-6 w-6" />
            </div>
          </div>
          <p className="text-xs text-green-600 mt-4 flex items-center font-medium">
            <span className="mr-1">↑ 12%</span> vs last week (Statewide)
          </p>
        </div>

        <div className="bg-white p-6 rounded-xl shadow-sm border border-slate-100">
          <div className="flex justify-between items-start">
            <div>
              <p className="text-sm text-slate-500 font-medium">Avg ICU Occupancy (AP)</p>
              <h3 className="text-3xl font-bold text-slate-900 mt-2">87%</h3>
            </div>
            <div className="p-3 bg-red-50 rounded-lg text-red-600">
              <Activity className="h-6 w-6" />
            </div>
          </div>
          <div className="w-full bg-slate-100 rounded-full h-1.5 mt-4">
            <div className="bg-red-500 h-1.5 rounded-full" style={{ width: '87%' }}></div>
          </div>
        </div>

        <div className="bg-white p-6 rounded-xl shadow-sm border border-slate-100">
          <div className="flex justify-between items-start">
            <div>
              <p className="text-sm text-slate-500 font-medium">AI Critical Alerts</p>
              <h3 className="text-3xl font-bold text-slate-900 mt-2">142</h3>
            </div>
            <div className="p-3 bg-amber-50 rounded-lg text-amber-600">
              <AlertTriangle className="h-6 w-6" />
            </div>
          </div>
          <p className="text-xs text-slate-500 mt-4">Across 26 Districts</p>
        </div>

        <div className="bg-white p-6 rounded-xl shadow-sm border border-slate-100">
          <div className="flex justify-between items-start">
            <div>
              <p className="text-sm text-slate-500 font-medium">Bed Availability</p>
              <h3 className="text-3xl font-bold text-slate-900 mt-2">3,200</h3>
            </div>
            <div className="p-3 bg-emerald-50 rounded-lg text-emerald-600">
              <BedDouble className="h-6 w-6" />
            </div>
          </div>
          <p className="text-xs text-slate-500 mt-4">Aggregated (KGH, GGH, etc.)</p>
        </div>
      </div>

      {/* Live Crisis Simulator & Referral Network */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
         
         {/* AI Crisis Simulator */}
         <div className="bg-gradient-to-br from-red-900 to-slate-900 rounded-xl p-6 text-white shadow-lg border border-red-800/50 relative overflow-hidden">
            <div className="relative z-10">
               <div className="flex items-center gap-3 mb-6">
                  <div className="p-2 bg-red-500/20 rounded-lg border border-red-500/30 animate-pulse">
                     <Network className="h-6 w-6 text-red-400" />
                  </div>
                  <div>
                     <h3 className="text-lg font-bold">AI Crisis Simulator</h3>
                     <p className="text-xs text-red-200">Live Strategic Analysis Engine</p>
                  </div>
               </div>

               {crisisPlan ? (
                  <div className="space-y-4">
                     <div className="bg-black/20 p-4 rounded-lg border border-white/5">
                        <p className="text-xs text-red-300 font-bold uppercase mb-1">Threat Assessment</p>
                        <p className="text-sm font-medium">{crisisPlan.threatAssessment}</p>
                     </div>
                     
                     <div>
                        <p className="text-xs text-amber-300 font-bold uppercase mb-2">Resource Re-allocation Orders</p>
                        <ul className="space-y-2">
                           {crisisPlan.resourceAllocations.map((alloc, i) => (
                              <li key={i} className="flex items-start gap-2 text-sm text-slate-200">
                                 <span className="text-amber-500 mt-1">→</span> {alloc}
                              </li>
                           ))}
                        </ul>
                     </div>

                     <div className="bg-white/10 p-4 rounded-lg border border-white/20 mt-4">
                        <p className="text-xs text-blue-300 font-bold uppercase mb-1">Draft Executive Order</p>
                        <p className="text-sm italic font-serif text-slate-100">"{crisisPlan.policyOrderDraft}"</p>
                        <div className="mt-3 flex gap-3">
                           <button className="px-3 py-1.5 bg-emerald-600 hover:bg-emerald-700 rounded text-xs font-bold shadow-sm transition-colors">Approve Order</button>
                           <button className="px-3 py-1.5 bg-white/10 hover:bg-white/20 rounded text-xs font-bold transition-colors">Modify</button>
                        </div>
                     </div>
                  </div>
               ) : (
                  <div className="text-center py-12 text-red-300">Running simulations...</div>
               )}
            </div>
         </div>

         {/* Live Referral Tracking */}
         <div className="bg-white p-6 rounded-xl border border-slate-200 shadow-sm flex flex-col">
            <h3 className="text-lg font-bold text-slate-800 mb-4 flex items-center gap-2">
               <Ambulance className="h-5 w-5 text-blue-600" /> Live Patient Logistics (108)
            </h3>
            <div className="flex-1 overflow-auto">
               <table className="w-full text-left">
                  <thead className="bg-slate-50 text-xs text-slate-500 uppercase font-bold">
                     <tr>
                        <th className="px-4 py-3">Patient / Priority</th>
                        <th className="px-4 py-3">Route</th>
                        <th className="px-4 py-3 text-right">Status</th>
                     </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-100">
                     {MOCK_REFERRALS.map(ref => (
                        <tr key={ref.id} className="hover:bg-slate-50">
                           <td className="px-4 py-3">
                              <p className="text-sm font-bold text-slate-800">{ref.patientName}</p>
                              <span className={`text-[10px] px-2 py-0.5 rounded font-bold ${
                                 ref.priority === 'CRITICAL' ? 'bg-red-100 text-red-700' : 'bg-amber-100 text-amber-700'
                              }`}>{ref.priority}</span>
                           </td>
                           <td className="px-4 py-3">
                              <div className="flex flex-col text-xs text-slate-600">
                                 <span>From: <strong>{ref.fromHospital}</strong></span>
                                 <span className="text-slate-400">↓</span>
                                 <span>To: <strong>{ref.toHospital}</strong></span>
                              </div>
                           </td>
                           <td className="px-4 py-3 text-right">
                              <span className={`text-xs font-bold flex items-center justify-end gap-1 ${
                                 ref.status === 'IN_TRANSIT' ? 'text-blue-600' : 'text-emerald-600'
                              }`}>
                                 {ref.status === 'IN_TRANSIT' && <Ambulance className="h-3 w-3 animate-pulse" />}
                                 {ref.status.replace('_', ' ')}
                              </span>
                           </td>
                        </tr>
                     ))}
                  </tbody>
               </table>
            </div>
            <button className="mt-4 w-full py-2 text-xs font-bold text-blue-600 bg-blue-50 hover:bg-blue-100 rounded transition-colors">
               View Full Logistics Map
            </button>
         </div>
      </div>

      {/* Charts */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <div className="bg-white p-6 rounded-xl shadow-sm border border-slate-100">
          <h3 className="text-lg font-semibold text-slate-900 mb-6">Patient Flow by Major City</h3>
          <div className="h-80 w-full">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={data}>
                <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e2e8f0" />
                <XAxis dataKey="name" axisLine={false} tickLine={false} tick={{fill: '#64748b', fontSize: 10}} dy={10} />
                <YAxis axisLine={false} tickLine={false} tick={{fill: '#64748b'}} />
                <Tooltip 
                  contentStyle={{ backgroundColor: '#fff', borderRadius: '8px', border: '1px solid #e2e8f0' }}
                  cursor={{ fill: '#f1f5f9' }}
                />
                <Bar dataKey="admissions" fill="#0ea5e9" radius={[4, 4, 0, 0]} name="New Admissions" />
                <Bar dataKey="discharges" fill="#cbd5e1" radius={[4, 4, 0, 0]} name="Discharges" />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>

        <div className="bg-white p-6 rounded-xl shadow-sm border border-slate-100">
          <h3 className="text-lg font-semibold text-slate-900 mb-6">Epidemic Watch (Dengue/Malaria)</h3>
          <div className="h-80 w-full">
            <ResponsiveContainer width="100%" height="100%">
              <LineChart data={riskData}>
                <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e2e8f0" />
                <XAxis dataKey="name" axisLine={false} tickLine={false} tick={{fill: '#64748b'}} dy={10} />
                <YAxis axisLine={false} tickLine={false} tick={{fill: '#64748b'}} />
                <Tooltip contentStyle={{ backgroundColor: '#fff', borderRadius: '8px', border: '1px solid #e2e8f0' }} />
                <Line type="monotone" dataKey="risk" stroke="#ef4444" strokeWidth={3} dot={{ r: 4, fill: '#ef4444' }} activeDot={{ r: 8 }} name="Case Spike Index" />
              </LineChart>
            </ResponsiveContainer>
          </div>
          <div className="mt-4 p-3 bg-red-50 text-red-800 text-sm rounded-lg flex items-center gap-2">
            <AlertTriangle className="h-4 w-4" />
            <span>AI Model Warning: Vector-borne spike detected in Coastal Districts (East Godavari).</span>
          </div>
        </div>
      </div>

      <div className="bg-slate-900 rounded-xl p-8 text-center text-slate-300">
         <Map className="h-12 w-12 mx-auto mb-4 opacity-50 text-emerald-400" />
         <h3 className="text-xl font-bold text-white">AP Geospatial Disease Heatmap</h3>
         <p className="max-w-md mx-auto mt-2">Interactive GIS map for Andhra Pradesh would load here, showing district-wise cluster outbreaks.</p>
      </div>
    </div>
  );
};
